#ifndef MSC_VERSION_HPP
#define MSC_VERSION_HPP

// Version configuration.
#define MEDIASOUPCLIENT_VERSION_MAJOR 3
#define MEDIASOUPCLIENT_VERSION_MINOR 4
#define MEDIASOUPCLIENT_VERSION_PATCH 1

#endif
